// File generated by Firebase CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// 기본 Firebase 구성 옵션
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase 웹 앱 설정
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Zj4PNPF80RL9qB1s7w5k3ZaBKVeYRo4',
    appId: '1:189136888100:web:e4af7ecbaa8beb37c9c3d1',
    messagingSenderId: '189136888100',
    projectId: 'pdf-learner',
    authDomain: 'pdf-learner.firebaseapp.com',
    storageBucket: 'pdf-learner.appspot.com',
    measurementId: 'G-LY7QXCN3ND',
  );

  /// Firebase Android 앱 설정
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWLZ5nGK5tXm0_FCoCYKOc50rKO_fUZhI',
    appId: '1:189136888100:android:e8a1b37a9a48d146c9c3d1',
    messagingSenderId: '189136888100',
    projectId: 'pdf-learner',
    storageBucket: 'pdf-learner.appspot.com',
  );

  /// Firebase iOS 앱 설정
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs4XXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:189136888100:ios:0000000000000000000000',
    messagingSenderId: '189136888100',
    projectId: 'pdf-learner',
    storageBucket: 'pdf-learner.appspot.com',
    iosClientId: 'XXXXX.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdfLearnerV2',
  );

  /// Firebase macOS 앱 설정
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs4XXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:189136888100:ios:0000000000000000000000',
    messagingSenderId: '189136888100',
    projectId: 'pdf-learner',
    storageBucket: 'pdf-learner.appspot.com',
    iosClientId: 'XXXXX.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdfLearnerV2',
  );
} 