// File generated by FlutterFire CLI.
// 실제 프로젝트에서는 Firebase CLI를 통해 생성된 파일을 사용하세요.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// PDF Learner 앱의 Firebase 구성 옵션
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 웹 플랫폼 설정
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpTt_AlV22_oeH9A2azgGfHAa19AoTjx0',
    appId: '1:189136888100:web:3c36f821c673adc13e93b1',
    messagingSenderId: '189136888100',
    projectId: 'pdf-learner',
    authDomain: 'pdf-learner.firebaseapp.com',
    storageBucket: 'pdf-learner.firebasestorage.app',
    measurementId: 'G-3LS46XS1LS',
  );

  // 안드로이드 플랫폼 설정
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAaUaNUqLKupp0Il9OHczUyb5VXDU2EhM',
    appId: '1:189136888100:android:2abd7262d4d575e03e93b1',
    messagingSenderId: '189136888100',
    projectId: 'pdf-learner',
    storageBucket: 'pdf-learner.firebasestorage.app',
  );

  // iOS 플랫폼 설정
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAaUaNUqLKupp0Il9OHczUyb5VXDU2EhM',
    appId: '1:189136888100:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '189136888100',
    projectId: 'pdf-learner',
    storageBucket: 'pdf-learner.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );

  // macOS 플랫폼 설정
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAaUaNUqLKupp0Il9OHczUyb5VXDU2EhM',
    appId: '1:189136888100:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '189136888100',
    projectId: 'pdf-learner',
    storageBucket: 'pdf-learner.firebasestorage.app',
    iosClientId: 'YOUR_MACOS_CLIENT_ID',
    iosBundleId: 'YOUR_MACOS_BUNDLE_ID',
  );
} 